//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace metaGamesInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class actions
    {
        public int id { get; set; }
        public string table_name { get; set; }
        public Nullable<int> register_id { get; set; }
        public string employee_action { get; set; }
        public string old_data { get; set; }
        public string new_data { get; set; }
        public string short_description { get; set; }
        public Nullable<System.DateTime> action_date { get; set; }
        public Nullable<int> id_employee { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
