//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace metaGamesInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups_permission
    {
        public int id { get; set; }
        public Nullable<int> id_groups { get; set; }
        public Nullable<int> id_permission { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual permission permission { get; set; }
    }
}
