//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace metaGamesInventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class metaGamesInventoryAlterEntities : DbContext
    {
        public metaGamesInventoryAlterEntities()
            : base("name=metaGamesInventoryAlterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actions> actions { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<discount> discount { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<groups_permission> groups_permission { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<orders_product> orders_product { get; set; }
        public virtual DbSet<orders_tax> orders_tax { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_category> product_category { get; set; }
        public virtual DbSet<provider> provider { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tax> tax { get; set; }
    }
}
