//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace metaGamesInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.orders_product = new HashSet<orders_product>();
            this.orders_tax = new HashSet<orders_tax>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<double> amount_untaxed { get; set; }
        public Nullable<double> amount_tax { get; set; }
        public Nullable<double> amount_total { get; set; }
        public string transaction_type { get; set; }
        public string order_state { get; set; }
        public string third { get; set; }
        public Nullable<int> id_employee { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders_product> orders_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders_tax> orders_tax { get; set; }
    }
}
