//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace metaGamesInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_product
    {
        public int id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<double> amount_discount { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<int> id_discount { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<int> id_product { get; set; }
    
        public virtual discount discount { get; set; }
        public virtual orders orders { get; set; }
        public virtual product product { get; set; }
    }
}
